let objects = [{
        id: 1,
        media: ["./videos/imgs3.jpg",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 1002,
        likes: 999,
        save: false,
    },
    {
        id: 2,
        media: ["./videos/imgs2.jpg",
            "./videos/landscape4.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 456,
        likes: 856,
        save: false,
    },
    {
        id: 3,
        media: ["./videos/imgs3.jpg", ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 656,
        likes: 348,
        save: false,
    },
    {
        id: 4,
        media: ["./videos/imgs4.jpg",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 654,
        likes: 254,
        save: false,
    },
    {
        id: 5,
        media: ["./images/imgs5.jpg",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 2035,
        likes: 468,
        save: false,
    },
    {
        id: 6,
        media: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 2364,
        likes: 56,
        save: false,
    },
    {
        id: 7,
        media: ["./images/imgs6.jpg",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 456,
        likes: 345,
        save: false,
    },
    {
        id: 8,
        media: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80",
            "./videos/landscape3.mp4"
        ],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 684,
        likes: 354,
        save: false,
    },
    {
        id: 9,
        media: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80"],
        name: "Landscapes",
        post: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil earum, unde, adipisci, quo dolor sapiente beatae quod iure optio cum magni. Dicta praesentium aliquam fuga possimus, fugiat voluptates impedit pariatur!",
        view: 846,
        likes: 952,
        save: false,
    },
]